# X_DOWNLOAD_PLACEHOLDER_X
  INST64_X_MODULE_UPPER_X_TARGET="$DEV_LIB_X_MODULE_UPPER_X_TARGET" \
    INST64_X_MODULE_UPPER_X_SYSTEM_WIDE='NO' \
    "${DEV_LIB_X_MODULE_UPPER_X_INSTALLER}"

# X_INIT_PLACEHOLDER_X
  bl64_check_file "$DEV_LIB_X_MODULE_UPPER_X_INSTALLER"
