jobs:
  test-X_MODULE_X:
    strategy:
      fail-fast: false
      matrix:
        target:
          - "X_VALUE_X"
    steps:

      - name: "Run tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-X_MODULE_X &&
          ./bin/dev-test-X_MODULE_X $DEV_TEST_X_MODULE_UPPER_X_CONTAINER_${{matrix.target}} ${DEV_TEST_X_MODULE_UPPER_X_CASES}/${{matrix.target}}
