#!/usr/bin/env bash

source test/lib/runtime.bash

#
# Prepare Test
#

source_lib=''
if [[ -v DEV_TEST_BASH_CONTAINER_ENVIRONMENT && -n "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" && -d "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" ]]; then
  source_lib="$DEV_ENV_BASH_CONTAINER_PATH_SRC"
else
  source_lib='src'
fi

at64root="${HOME}/at64"
install_target="${at64root}/devbin64"
test_target="${HOME}/repo"
mkdir -p \
  "$install_target" \
  "${install_target}/bin" \
  "$test_target" &&
  cp -r "${source_lib}/lib" "$install_target" &&
  cp "${source_lib}/lib/devbin64/bin/dev-bootstrap" "${install_target}/bin" &&
  cd "$test_target" ||
  exit $?

#
# Run Test
#

export DEV_BOOTSTRAP_PATH_ROOT="$install_target"
"${install_target}/bin/dev-bootstrap"
