#!/usr/bin/env bash

# Test: repeat bootstrap
./test/lib/check.bash &&
  source test/lib/runtime.bash &&
  ./test/lib/install.bash &&
  cd "$TEST_TARGET" &&
  [[ -f .devbin64 ]] &&
  "${TEST_INSTALL_TARGET}/bin/dev-bootstrap" >/dev/null 2>&1
