#!/usr/bin/env bash

source test/lib/runtime.bash &&
  ./test/lib/install.bash &&
  cd "$TEST_TARGET" ||
  exit $?

pwd
ls -al

[[ -d bin ]] &&
  [[ -d build ]] &&
  [[ -d docs ]] &&
  [[ -d etc ]] &&
  [[ -d lib ]] &&
  [[ -d logs ]] &&
  [[ -d src ]] &&
  [[ -d test ]] &&
  [[ -d tmp ]] &&
  [[ -d var ]] &&
  [[ -d vault ]] ||
  exit 1

[[ -f .gitignore ]] &&
  [[ -f .dev.env ]] &&
  [[ -f dot.dev.env ]] &&
  [[ -f dot.gitignore ]] &&
  [[ -f dot.local.env ]] &&
  [[ -f dot.secrets.env ]]
