#!/usr/bin/env bash

# Test: repeat bootstrap
source test/lib/runtime.bash &&
  ./test/lib/install.bash &&
  cd "$TEST_TARGET" &&
  [[ -f .devbin64 ]] &&
  "${install_target}/bin/dev-bootstrap" >/dev/null 2>&1
