#!/usr/bin/env bash

source test/lib/check.bash

#
# Prepare Test
#

install_target='/tmp/devbin64'
test_target="${HOME}/repo"
mkdir -p \
  "$install_target" \
  "${install_target}/bin" \
  "$test_target" &&
  cp -r "${DEV_ENV_BASH_CONTAINER_PATH_SRC}/lib" "$install_target" &&
  cp "${DEV_ENV_BASH_CONTAINER_PATH_SRC}/lib/devbin64/bin/dev-bootstrap" "${install_target}/bin" &&
  cd "$test_target" ||
  exit $?

#
# Run Test
#

export DEV_BOOTSTRAP_PATH_ROOT="$install_target"
"${install_target}/bin/dev-bootstrap"
