#!/usr/bin/env bash

./test/lib/check.bash &&
  source test/lib/runtime.bash &&
  ./test/lib/install.bash &&
  cd "$TEST_TARGET" ||
  exit $?

echo '_xxx_syntax_error export _SECRET_TEST="TEST_VALUE"' >vault/.secrets.env

! source ./bin/dev-set &&
  [[ -z "$_SECRET_TEST" ]]
