#!/usr/bin/env bash

export DEV_BOOTSTRAP_MODULES=''

DEV_BOOTSTRAP_MODULES="$(ls -1 "src/lib")" &&
  ./test/lib/check.bash &&
  source test/lib/runtime.bash &&
  ./test/lib/install.bash &&
  cd "$TEST_TARGET" ||
  exit $?

#
# Prepare Test
#

[[ -f .devbin64-modules ]]
