#!/usr/bin/env bash

export DEV_BOOTSTRAP_MODULES=''
declare module=''

DEV_BOOTSTRAP_MODULES="$(ls -1 "src/lib")" &&
  ./test/lib/check.bash &&
  source test/lib/runtime.bash &&
  source test/lib/reset-env.bash &&
  ./test/lib/install.bash &&
  cd "$TEST_TARGET" ||
  exit $?

source ./bin/dev-set &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-xsv.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-bsh.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" ||
  exit 1

for module in $DEV_BOOTSTRAP_MODULES; do
  [[ "$module" =~ (devbin64|installer64|bashlib64|project) ]] && continue
  source "${TEST_TARGET}/bin/dev-env-${module}" ||
    exit $?
done
