#!/usr/bin/env bash

#
# Prepare Test
#

if [[ "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" != 'ON' ]]; then
  echo 'error: Test must be executed inside a container'
  exit 1
fi

install_target='/tmp/devbin64'
test_target="${HOME}/repo"
modules="$(ls -1 "${DEV_ENV_BASH_CONTAINER_PATH_SRC}/lib")"
mkdir -p \
  "$install_target" \
  "${install_target}/bin" \
  "$test_target" &&
  cp -r "${DEV_ENV_BASH_CONTAINER_PATH_SRC}/lib" "$install_target" &&
  cp "${DEV_ENV_BASH_CONTAINER_PATH_SRC}/lib/devbin64/bin/dev-bootstrap" "${install_target}/bin" &&
  echo "$modules" >"$test_target/.devbin64-modules" &&
  cd "$test_target" ||
  exit $?

#
# Run Test
#

export DEV_BOOTSTRAP_PATH_ROOT="$install_target"
"${install_target}/bin/dev-bootstrap"
