#!/usr/bin/env bash

echo "WARNING: running on local host"

sudo rm -rf /opt/devbin64
sudo mkdir /opt/devbin64 /opt/devbin64/bin &&
sudo cp -r ./src/lib /opt/devbin64 &&
sudo cp ./src/lib/devbin64/bin/dev-bootstrap /opt/devbin64/bin
