#!/usr/bin/env bash

source test/lib/runtime.bash

export DEV_BOOTSTRAP_PATH_ROOT='/project/src'
cd src/lib
modules="$(ls -1 | grep -v devbin64)"

./test/adhoc/user_reset.sh

cd "$HOME"
mkdir test-repo
cd test-repo
echo "$modules" > .devbin64-modules

/project/src/lib/devbin64/bin/dev-bootstrap
