---
# Template: 3.1.0
name: "Test / Bash"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"
      - "test/**"

jobs:
  test-batscore:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        run: "./bin/dev-build-bash"

      - name: "Run tests"
        run: "./bin/dev-test-testmansh"
...
