---
# Template: 3.2.0
name: "Test / TestManSH"

env:
  DEV_CICD_DEBUG: ""

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"
      - "test/batscore/**"

jobs:
  test-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare dev environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        run: "./bin/dev-build-bash"

      - name: "Run tests"
        run: "./bin/dev-test-testmansh"
...
