#!/usr/bin/env bash
# doc # Use any of the following variables to get access to project files:
# doc #   "$DEV_ENV_BASH_CONTAINER_PATH_SRC"
# doc #   "$DEV_ENV_BASH_CONTAINER_PATH_ROOT"
# doc #   "$DEV_ENV_BASH_CONTAINER_PATH_TEST"

#
# Prepare Test
#

if [[ "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" != 'ON' ]]; then
  echo 'error: Test must be executed inside a container'
  exit 1
fi

#
# Run Test
#
