---
# Template: 1.3.0
name: "Release"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"
  DEV_LIB_GH_BIN: "gh"

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions: "write-all"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare environment"
        run: "./bin/dev-lib-base"

      # X_BUILD_PLACEHOLDER_X

      # X_PACK_PLACEHOLDER_X

      - name: "Create GitHub release"
        run: "./bin/dev-release ${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
