# X_GLOBAL_PLACEHOLDER_X
# shellcheck disable=SC2154
{
  # X_TASK_TITLE_X / X_MODULE_TITLE_X / X_VAR_DESCRIPTION_X
  export DEV_X_TASK_UPPER_X_X_MODULE_UPPER_X_X_VAR_UPPER_X="X_VALUE_X"
}

# X_LOCALS_PLACEHOLDER_X
# shellcheck disable=SC2154
{
  # X_TASK_TITLE_X / X_MODULE_TITLE_X / X_VAR_DESCRIPTION_X
  export DEV_X_TASK_UPPER_X_X_MODULE_UPPER_X_X_VAR_UPPER_X="X_VALUE_X"
}

# X_SECRETS_PLACEHOLDER_X
# shellcheck disable=SC2154
{
  # X_TASK_TITLE_X / X_MODULE_TITLE_X / X_VAR_DESCRIPTION_X
  export DEV_X_TASK_UPPER_X_X_MODULE_UPPER_X_X_VAR_UPPER_X="X_VALUE_X"
}
